DROP DATABASE IF EXISTS tarefa;
CREATE DATABASE tarefa;
USE tarefa;

CREATE TABLE tarefas (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tarefa VARCHAR(100)
);

INSERT INTO tarefas VALUES (DEFAULT, "LIMPAR CASA")
INSERT INTO tarefas VALUES (DEFAULT, "FAZER COMPRAS")
    
